version: '3.8'

services:
  core:
    build: .
    links:
      - db
    env_file:
      - .env.example
    ports:
      - 8080:8080
  db:
    image: postgres:11-alpine
    env_file:
      - .env.example
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432