version: '2.1'
services:
  db:
    container_name: roadmaps_db
    image: postgres:alpine
    restart: always
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres 2>&1 | grep \"accepting connections\" || exit 1"]
      interval: 10s
      timeout: 15s
      retries: 3
    networks:
      - roadmaps-core
  backend:
    container_name: roadmaps-core
    image: edu.roadmaps/roadmaps-core:v0.1
    restart: always
    volumes:
    - /opt/roadmaps/logs:/logs
    cap_add:
      - SYS_PTRACE
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:${POSTGRES_PORT}/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent localhost:8080/actuator/health 2>&1 | grep UP || exit 1"]
      interval: 90s
      timeout: 5s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
    networks:
      - roadmaps-core

networks:
  roadmaps-core: