version: '3.8'

services:
  core:
    container_name: core
    build: .
    links:
      - db
    env_file:
      - .env.example
    ports:
      - "8080:8080"

  db:
    container_name: db
    image: postgres:alpine
    env_file:
      - .env.example
    ports:
      - "5432:5432"