version: '3.8'

services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
  core:
    image: roadmapsedu/rmpscore:latest
    depends_on:
      - db
    environment:
      - JAVA_TOOL_OPTIONS="-Dspring.datasource.url=${POSTGRES_URL}" "-Dspring.datasource.password=${POSTGRES_PASSWORD}" "-Dspring.datasource.username=${POSTGRES_USER}"