spring:
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/roadmaps_db
    username: postgres
    password: mysecretpassword

springdoc:
  api-docs:
    path: /api/swagger
  swagger-ui:
    path: /api/swagger-ui

server:
  forward-headers-strategy: NATIVE

jwt:
  secret: ${JWT_SECRET}
  tokenValidDays: ${JWT_TOKEN_VALID_DAYS}

google:
  clientId: ${GOOGLE_CLIENT_ID}
  clientSecret: ${GOOGLE_CLIENT_SECRET}
  redirectUri: ${GOOGLE_REDIRECT_URI}
  appName: ${GOOGLE_APP_NAME}