spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      javax:
        persistence:
          jdbc:
            driver: org.postgresql.Driver
            url: ${POSTGRES_URL}
            user: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}

springdoc:
  api-docs:
    path: /api/swagger
  swagger-ui:
    path: /api/swagger-ui

server:
  forward-headers-strategy: NATIVE

jwt:
  secret: 123123123123123123123123123123123123123123123123123123
  tokenValidDays: 365

google:
  clientId: ${GOOGLE_CLIENT_ID}
  clientSecret: ${GOOGLE_CLIENT_SECRET}
  redirectUri: http://localhost:3000
  appName: ${GOOGLE_APP_NAME}