spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/roadmaps_db
    username: roadmaps
    password: roadmaps

springdoc:
  api-docs:
    path: /api/swagger
  swagger-ui:
    path: /api/swagger-ui

server:
  forward-headers-strategy: NATIVE

jwt:
  secret: ${JWT_SECRET}
  tokenValidDays: ${JWT_TOKEN_VALID_DAYS}

google:
  clientId: ${GOOGLE_CLIENT_ID}
  clientSecret: ${GOOGLE_CLIENT_SECRET}
  redirectUri: http://localhost:3000
  appName: ${GOOGLE_APP_NAME}