spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

springdoc:
  api-docs:
    path: /api/swagger
  swagger-ui:
    path: /api/swagger-ui

server:
  forward-headers-strategy: NATIVE

jwt:
  secret: 123123123123123123123123123123123123123123123123123123
  tokenValidDays: 365

google:
  clientId: ${GOOGLE_CLIENT_ID}
  clientSecret: ${GOOGLE_CLIENT_SECRET}
  redirectUri: ${GOOGLE_REDIRECT_URI}
  appName: ${GOOGLE_APP_NAME}
