spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/roadmaps_db?currentSchema=core
    password: roadmaps
    username: roadmaps
  liquibase:
    change-log: 'classpath:/db.changelog/changelog.xml'