spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

springdoc:
  api-docs:
    path: /api/swagger
  swagger-ui:
    path: /api/swagger-ui

server:
  forward-headers-strategy: NATIVE

google:
  clientId: ${GOOGLE_CLIENT_ID}
  clientSecret: ${GOOGLE_CLIENT_SECRET}
  redirectUri: ${GOOGLE_REDIRECT_URI}
  appName: ${GOOGLE_APP_NAME}

authorization:
  writeDefaultUserJWTOnStartup: true
  tokenLifeTimeInDays: 60
  generateKeyPair: true
  keyPair:
    public: ${JWT_PUBLIC_KEY}
    private: ${JWT_PRIVATE_KEY}